# Generated by Django 4.2.3 on 2023-07-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserv2',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
