# Generated by Django 4.2.3 on 2023-07-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated_by',
            field=models.CharField(max_length=50),
        ),
    ]
