# Generated by Django 4.2.3 on 2023-07-07 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='updated_by',
        ),
    ]
